# Generated by Django 3.2 on 2023-10-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=20, verbose_name='知识库id')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('uuid', models.CharField(max_length=20, verbose_name='uuid,唯一值')),
                ('prev_uuid', models.CharField(blank=True, max_length=20, null=True, verbose_name='上一节点值')),
                ('sibling_uuid', models.CharField(blank=True, max_length=20, null=True, verbose_name='下一节点值')),
                ('parent_uuid', models.CharField(blank=True, max_length=20, null=True, verbose_name='父节点值')),
                ('child_uuid', models.CharField(blank=True, max_length=20, null=True, verbose_name='子节点值')),
                ('url', models.CharField(max_length=20, verbose_name='拼接路径URL')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='知识库名称')),
                ('repo_id', models.CharField(max_length=20, verbose_name='知识库id')),
                ('is_selected', models.BooleanField(verbose_name='是否勾选')),
                ('is_download', models.BooleanField(default=False, verbose_name='是否下载')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100, verbose_name='个人空间名称')),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wiki_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, verbose_name='文档url')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
